version: '3.7'
services:
  postgres:
      container_name: postgres
      image: postgres:10.5
      privileged: true
      restart: always
      environment:
        - POSTGRES_DB=orientacao-bucal
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data