version: '3.7'
services:

  backend:
      container_name: backend
      build:
        context: .
      depends_on:
        - postgres
      environment:
        - POSTGRES_DB=orientacao-bucal
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
        - SERVER_PORT=3000
      ports:
        - '3000:3000'
      networks:
        - backend

  postgres:
      container_name: postgres
      image: postgres:10.5
      restart: always
      environment:
        - POSTGRES_DB=orientacao-bucal
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      networks: 
        - backend

networks:
  backend:
    driver: bridge
